### ISSUE TITLE
package installation leads to inconsistent dpkg state in Ubuntu 18.04

### ISSUE THREAD

**Issue by gembutterfly** [juhaku/loginized#4] opened 2018-05-07 11:38 UTC

**Comment by juhaku** [comment] 2018-05-07 15:39
I'll take a look at this and get back when I have some sort of resolution available. Thanks for letting me know.

**Comment by juhaku** [comment] 2018-05-08 18:19
I installed it to fresh install of Ubuntu 18.04 without any issues. No matter whether to install it via Ubuntu Software or via command line. Before ubuntu 18.04 the required `glib-compile-resources` command found from package `libglib2.0-bin` but in ubuntu 18.04 it is found from `libglib2.0-dev-bin` package. After installing that dependency manually it should work as fine.

Please specify if the issue is fixed with this help or if this is not the issue at all. In case could you specify in more detail what is going wrong and where?

**Comment by serapis5** [comment] 2018-05-08 18:42
Thank you Juha.  I will try this solution as soon as I am able and get back with you.

Bart



Sent from my Sprint Samsung Galaxy S8+.


-------- Original message --------

**Comment by serapis5** [comment] 2018-05-08 22:59
Juha,
Thank you for your quick response.  It worked like a charm and I have my login screen again.  Have a wonderful day.

Bart



Sent from my Sprint Samsung Galaxy S8+.


-------- Original message --------

**Comment by juhaku** [comment] 2018-05-08 23:25
Great to hear. 

-Juha

**Closed** 2018-05-10 12:35 UTC
